config/routes.rb
Rails.application.routes.draw do
  resources :calendars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "calendars#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
	require 'Date'
	validates :name, presence: true, uniqueness: true
	validates :genre, presence: true
	validate :cant_be_in_the_past

	def cant_be_in_the_past
    if date.present? && date < Date.today
      errors.add(:date, "No puede ser en el pasado")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]

  # GET /calendars
  # GET /calendars.json
  def index
    @calendars = Calendar.all
  end

  # GET /calendars/1
  # GET /calendars/1.json
  def show
  end

  # GET /calendars/new
  def new
    @calendar = Calendar.new
  end

  # GET /calendars/1/edit
  def edit
  end

  # POST /calendars
  # POST /calendars.json
  def create
    @calendar = Calendar.new(calendar_params)

    respond_to do |format|
      if @calendar.save
        format.html { redirect_to @calendar, notice: 'Calendar was successfully created.' }
        format.json { render :show, status: :created, location: @calendar }
      else
        format.html { render :new }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calendars/1
  # PATCH/PUT /calendars/1.json
  def update
    respond_to do |format|
      if @calendar.update(calendar_params)
        format.html { redirect_to @calendar, notice: 'Calendar was successfully updated.' }
        format.json { render :show, status: :ok, location: @calendar }
      else
        format.html { render :edit }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1
  # DELETE /calendars/1.json
  def destroy
    @calendar.destroy
    respond_to do |format|
      format.html { redirect_to calendars_url, notice: 'Calendar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendar
      @calendar = Calendar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calendar_params
      params.require(:calendar).permit(:date, :genre, :name, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_form.html.erb
<%= form_for(calendar) do |f| %>
  <% if calendar.errors.any? %>
    <div class="row">
      <div id="error_explanation" class="alert alert-danger col-12">
        <h2><%= pluralize(calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>

        <ul>
        <% calendar.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-12">
      <div class="field form-row form-group">
        <%= f.label :date, "Fecha:", class: "col-12" %>
        <%= f.datetime_select :date, {}, class: "form-control col" %>
      </div>

      <div class="field form-group">
        <%= f.label :genre %>
        <%= f.text_field :genre, class: "form-control" %>
      </div>

      <div class="field form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="field form-group">
        <%= f.label :location %>
        <%= f.text_field :location, class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit "Subir", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/calendars/edit.html.erb
<h1>Editing Calendar</h1>

<%= render 'form', calendar: @calendar %>

<%= link_to 'Show', @calendar, class: "btn btn-primary" %> |
<%= link_to 'Back', calendars_path %>

app/views/calendars/index.html.erb
<h1>Calendarios</h1>

<div class="row align-items-end">
  <% @calendars.each do |calendar| %>
    <div class="col-4">
      <h2><%= calendar.name %></h2>
      <p class="
        <%=
          if calendar.genre == 'evento'
            'text-success'

          elsif calendar.genre == 'cumpleaños'
            'text-warning'

          else 
            'text-primary'

          end
        %>
      ">
        <%= calendar.genre %>
      </p>
      <p><%= calendar.date %></p>
      <%= link_to 'Show', calendar, class: "btn btn-success" %>
      <%= link_to 'Edit', edit_calendar_path(calendar), class: "btn btn-info" %>
      <%= link_to 'Destroy', calendar, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    </div>
  <% end %>
</div>
<hr>
<div>
  <%= link_to 'New Calendar', new_calendar_path, class: "btn btn-primary" %>
</div>

app/views/calendars/new.html.erb
<h1>New Calendar</h1>

<%= render 'form', calendar: @calendar %>

<%= link_to 'Back', calendars_path %>

app/views/calendars/show.html.erb
<div>
  <h2><%= @calendar.name %></h2>
  <p class="
    <%=
      if @calendar.genre == 'evento'
        'text-success'

      elsif @calendar.genre == 'cumpleaños'
        'text-warning'

      else 
        'text-primary'

      end
    %>
  ">
    <%= @calendar.genre %>
  </p>
  <p><%= @calendar.date %></p>
  <%= link_to 'Edit', edit_calendar_path(@calendar), class: "btn btn-info" %>
  <%= link_to 'Destroy', @calendar, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
</div>

<div>
	<%= link_to 'Back', calendars_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventosAyudantiaG5</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

		<div class="container">
			<ul class="nav nav-tabs">
				<li class="nav-item">
					<a class="nav-link <%= 'active' if current_page?(calendars_path) %>" href="<%= calendars_path %>">Todos los Eventos</a>
				</li>
				<li class="nav-item">
					<a class="nav-link <%= 'active' if current_page?(new_calendar_path) %>" href="<%= new_calendar_path %>">Nuevo evento</a>
				</li>
			</ul>

			<% if notice %>
			  <div class="alert alert-primary" role="alert">
			    <p id="notice"><%= notice %></p>
			  </div>
			<% end %>

    	<%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>